/*
 EEEEEEEE       AA         SSSSSS  YY    YY       SSSSSS       AA        LL        UU    UU  DDDDD
 EE          AA    AA      SS       YY  YY        SS        AA    AA     LL        UU    UU  DD   DDD
 EEEEEEEE   AAA    AAA     SSSSSS     YY          SSSSSS   AAA    AAA    LL        UU    UU  DD   DDDD
 EE        AAAAAAAAAAAA        SS     YY              SS  AAAAAAAAAAAA   LL        UU    UU  DD  DDDD
 EEEEEEEE AAAA     AAAAA   SSSSSS     YY          SSSSSS AAAA     AAAAA  LLLLLLLL  UUUUUUUU  DDDDDD
 
 Script Sql para Software Easy Salud 2018
 Version: 1.0
*/

CREATE DATABASE EASYSALUD;
USE EASYSALUD;

DROP TABLE IF EXISTS ET_REPRESENTANTE_SUCURSAL;
DROP TABLE IF EXISTS ET_REPRESENTANTES;
DROP TABLE IF EXISTS ET_PUNTUACION;
DROP TABLE IF EXISTS ET_PAGOS_SUCURSAL;
DROP TABLE IF EXISTS ET_PAGOS;
DROP TABLE IF EXISTS ET_PACIENTE;
DROP TABLE IF EXISTS ET_PLANES;
DROP TABLE IF EXISTS ET_MENSAJES;
DROP TABLE IF EXISTS ET_SOLICITUD;
DROP TABLE IF EXISTS ET_ESTADO;
DROP TABLE IF EXISTS ET_MENSAJES_FARMACIAS;
DROP TABLE IF EXISTS ET_SUCURSAL;
DROP TABLE IF EXISTS ET_FARMACIA;
DROP TABLE IF EXISTS ET_EQUIPAMIENTO;
DROP TABLE IF EXISTS ET_DISPONIBILIDAD;
DROP TABLE IF EXISTS ET_ESTUDIOS_PROFESIONAL;
DROP TABLE IF EXISTS ET_PROFESIONAL;
DROP TABLE IF EXISTS ET_ESPECIALIDAD;
DROP TABLE IF EXISTS ET_NIVEL_ESTUDIOS;
DROP TABLE IF EXISTS ET_INSTITUCIONES;
DROP TABLE IF EXISTS ET_ESPECIALIDAD;
DROP TABLE IF EXISTS ET_USUARIOS;
DROP TABLE IF EXISTS ET_ESTADO_CUENTA;
DROP TABLE IF EXISTS ET_TIPO_USUARIO;
DROP TABLE IF EXISTS ET_COMUNA;
DROP TABLE IF EXISTS ET_REGION;

CREATE TABLE ET_REGION(
	C_ID_REGION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_NOMBRE_REGION VARCHAR(50),
	S_ORDINAL_REGION VARCHAR(4),
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_COMUNA(
	C_ID_COMUNA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_REGION INT NOT NULL,
	D_NOMBRE_COMUNA VARCHAR(50) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_ESPECIALIDAD(
	C_ID_ESPECIALIDAD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_ESPECIALIDAD VARCHAR(100) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_TIPO_USUARIO(
	C_ID_TIPO_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_TIPO_USUARIO VARCHAR(50) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_ESTADO_CUENTA(
	C_ID_ESTADO_CUENTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_ESTADO_CUENTA VARCHAR(50) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_USUARIOS(
	C_ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_TIPO_USUARIO INT NOT NULL,
	C_ID_COMUNA INT NOT NULL,
	C_ID_ESTADO_CUENTA INT NOT NULL,
	S_RUN_USUARIO VARCHAR(10),
	D_NOMBRE_USUARIO VARCHAR(50) NOT NULL,
	D_APELLIDO_USUARIO VARCHAR(50) NOT NULL,
	D_EMAIL_USUARIO VARCHAR(50) NOT NULL,
	N_TELEFONO_USUARIO INT,
	N_MOVIL_USUARIO INT NOT NULL,
	D_DIRECCION_USUARIO VARCHAR(100) NOT NULL,
	S_DEPTO_USARIO VARCHAR(10),
	F_FECHA_NACIMIENTO DATE NOT NULL,
	S_SEXO_USUARIO VARCHAR(1),
	D_CLAVE_USUARIO VARCHAR (50) NOT NULL,
	D_CODIGO_USUARIO VARCHAR(50) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_NIVEL_ESTUDIOS(
	C_ID_NIVEL_ESTUDIOS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_NOMBRE_NIVEL_ESTUDIOS VARCHAR(100) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_INSTITUCIONES(
	C_ID_INSTITUCIONES INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_NOMBRE_INSTITUCION VARCHAR(250) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_PROFESIONAL(
	C_ID_PROFESIONAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	C_ID_COMUNA INT NOT NULL,
	D_IMAGEN VARCHAR(100) NULL,
	D_DESCRIPCION VARCHAR(1500) NULL,
	L_ACTIVO BOOLEAN NOT NULL,
	L_PREMIUM BOOLEAN NOT NULL,
	D_DIRECCION_DISPONIBILIDAD VARCHAR(100) NOT NULL,
	N_LATITUD FLOAT(40,20) NULL ,
	N_LONGITUD FLOAT(40,20) NULL ,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_ESTUDIOS_PROFESIONAL(
	C_ID_ESTUDIOS_PROFESIONAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_PROFESIONAL INT NOT NULL,
	C_ID_ESPECIALIDAD INT NOT NULL,
	C_ID_NIVEL_ESTUDIOS INT NOT NULL,
	C_ID_INSTITUCIONES INT NOT NULL,
	D_TITULO VARCHAR(255) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_DISPONIBILIDAD(
	C_ID_DISPONIBILIDAD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_PROFESIONAL INT NOT NULL,
	L_LUNES BOOLEAN NOT NULL,
	L_MARTES BOOLEAN NOT NULL,
	L_MIERCOLES BOOLEAN NOT NULL,
	L_JUEVES BOOLEAN NOT NULL,
	L_VIERNES BOOLEAN NOT NULL,
	L_SABADO BOOLEAN NOT NULL,
	L_DOMINGO BOOLEAN NOT NULL,
	F_HORAS_DESDE INT NOT NULL,
	F_MINUTOS_DESDE INT NOT NULL,
	F_HORAS_HASTA INT NOT NULL,
	F_MINUTOS_HASTA INT NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_EQUIPAMIENTO(
	C_ID_EQUIPAMIENTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_PROFESIONAL INT NOT NULL,
	D_EQUIPO VARCHAR(255) NOT NULL,
	D_IMAGEN VARCHAR(100) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_FARMACIA(
	C_ID_FARMACIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	D_NOMBRE_FARMACIA VARCHAR(255) NOT NULL,
	D_WEB_FARMACIA VARCHAR(100),
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_SUCURSAL(
	C_ID_SUCURSAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_FARMACIA INT NOT NULL,
	C_ID_COMUNA INT NOT NULL,
	D_NOMBRE_SUCURSAL VARCHAR(255) NOT NULL,
	D_DIRECCION_SUCURSAL VARCHAR(255) NOT NULL,
	N_TELEFONO_SUCURSAL INT NOT NULL,
	N_LATITUD FLOAT( 40, 20 ) NOT NULL ,
	N_LONGITUD FLOAT( 40, 20 ) NOT NULL ,
	L_ACTIVA BOOLEAN NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_ESTADO(
	C_ID_ESTADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_NOMBRE_ESTADO VARCHAR(100) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_SOLICITUD(
	C_ID_SOLICITUD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	C_ID_PROFESIONAL INT NOT NULL,
	C_ID_ESTADO INT NOT NULL,
	C_PARA INT,
	F_FECHA_ATENCION DATE NOT NULL,
	F_HORAS INT NOT NULL,
	F_MINUTOS INT NOT NULL,
	D_ANOTACIONES_SOLICITUD VARCHAR(1900),
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_MENSAJES(
	C_ID_MENSAJE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO_ENVIA INT NOT NULL,
	C_ID_USUARIO_RECIBE INT NOT NULL,
	D_TITULO_MENSAJE VARCHAR(50) NOT NULL,
	D_MENSAJE VARCHAR(1000) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_MENSAJES_FARMACIAS(
	C_ID_MENSAJE_FARMACIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_SUCURSAL INT NOT NULL,
	C_ID_USUARIO_ENVIA INT NOT NULL,
	D_MENSAJE_FARMACIA VARCHAR(255) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_PLANES(
	C_ID_PLAN INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	D_NOMBRE_PLAN VARCHAR(255) NOT NULL,
	C_DURACION INT NOT NULL,
	L_TIPO VARCHAR(3) NOT NULL,
	C_VALOR INT NOT NULL,
	L_ACTIVO BOOLEAN NOT NULL,
	S_TIPO_PLAN VARCHAR(1) NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_PAGOS(
	C_ID_PAGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	C_ID_PLAN INT NOT NULL,
	F_FECHA_VENCIMIENTO DATE NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_PAGOS_SUCURSAL(
	C_ID_PAGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	C_ID_PLAN INT NOT NULL,
	C_ID_SUCURSAL INT NOT NULL,
	F_FECHA_VENCIMIENTO DATE NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_PACIENTE(
	C_ID_PACIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	C_ID_COMUNA INT NOT NULL,
	D_NOMBRE_PACIENTE VARCHAR(50) NOT NULL,
	D_APELLIDO_PACIENTE VARCHAR(50) NOT NULL,
	N_TELEFONO_PACIENTE INT,
	N_MOVIL_PACIENTE INT NOT NULL,
	D_DIRECCION_PACIENTE VARCHAR(100) NOT NULL,
	S_DEPTO_PACIENTE VARCHAR(10),
	S_SEXO_PACIENTE VARCHAR(1),
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_PUNTUACION(
	C_ID_PUNTUACION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_SOLICITUD INT NOT NULL,
	N_PUNTAJE FLOAT(2,1) NOT NULL,
	D_COMENTARIO VARCHAR(500) NULL,
	L_VISIBILIDAD BOOLEAN NOT NULL,
	F_FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_REPRESENTANTES(
	C_ID_REPRESENTANTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_USUARIO INT NOT NULL,
	C_ID_FARMACIA INT NOT NULL,
	F_FECHA_REGISTRO_REPRESENTANTE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE ET_REPRESENTANTE_SUCURSAL(
	C_ID_REPRESENTANTE_SUCURSAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_ID_REPRESENTANTE INT NOT NULL,
	F_FECHA_REGISTRO_REPRESENTANTE_SUCURSAL TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

ALTER TABLE ET_COMUNA ADD FOREIGN KEY (C_ID_REGION) REFERENCES ET_REGION(C_ID_REGION);
ALTER TABLE ET_USUARIOS ADD FOREIGN KEY (C_ID_TIPO_USUARIO) REFERENCES ET_TIPO_USUARIO(C_ID_TIPO_USUARIO);
ALTER TABLE ET_USUARIOS ADD FOREIGN KEY (C_ID_COMUNA) REFERENCES ET_COMUNA(C_ID_COMUNA);
ALTER TABLE ET_USUARIOS ADD FOREIGN KEY (C_ID_ESTADO_CUENTA) REFERENCES ET_ESTADO_CUENTA(C_ID_ESTADO_CUENTA);
ALTER TABLE ET_PROFESIONAL ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_PROFESIONAL ADD FOREIGN KEY (C_ID_COMUNA) REFERENCES ET_COMUNA(C_ID_COMUNA);
ALTER TABLE ET_ESTUDIOS_PROFESIONAL ADD FOREIGN KEY (C_ID_PROFESIONAL) REFERENCES ET_PROFESIONAL(C_ID_PROFESIONAL);
ALTER TABLE ET_ESTUDIOS_PROFESIONAL ADD FOREIGN KEY (C_ID_ESPECIALIDAD) REFERENCES ET_ESPECIALIDAD(C_ID_ESPECIALIDAD);
ALTER TABLE ET_ESTUDIOS_PROFESIONAL ADD FOREIGN KEY (C_ID_NIVEL_ESTUDIOS) REFERENCES ET_NIVEL_ESTUDIOS(C_ID_NIVEL_ESTUDIOS);
ALTER TABLE ET_ESTUDIOS_PROFESIONAL ADD FOREIGN KEY (C_ID_INSTITUCIONES) REFERENCES ET_INSTITUCIONES(C_ID_INSTITUCIONES);
ALTER TABLE ET_DISPONIBILIDAD ADD FOREIGN KEY (C_ID_PROFESIONAL) REFERENCES ET_PROFESIONAL(C_ID_PROFESIONAL);
ALTER TABLE ET_EQUIPAMIENTO ADD FOREIGN KEY (C_ID_PROFESIONAL) REFERENCES ET_PROFESIONAL(C_ID_PROFESIONAL);
ALTER TABLE ET_FARMACIA ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_SUCURSAL ADD FOREIGN KEY (C_ID_FARMACIA) REFERENCES ET_FARMACIA(C_ID_FARMACIA);
ALTER TABLE ET_SUCURSAL ADD FOREIGN KEY (C_ID_COMUNA) REFERENCES ET_COMUNA(C_ID_COMUNA);
ALTER TABLE ET_SOLICITUD ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_SOLICITUD ADD FOREIGN KEY (C_ID_PROFESIONAL) REFERENCES ET_PROFESIONAL(C_ID_PROFESIONAL);
ALTER TABLE ET_SOLICITUD ADD FOREIGN KEY (C_ID_ESTADO) REFERENCES ET_ESTADO(C_ID_ESTADO);
ALTER TABLE ET_MENSAJES ADD FOREIGN KEY (C_ID_USUARIO_ENVIA) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_MENSAJES ADD FOREIGN KEY (C_ID_USUARIO_RECIBE) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_MENSAJES_FARMACIAS ADD FOREIGN KEY (C_ID_SUCURSAL) REFERENCES ET_SUCURSAL(C_ID_SUCURSAL);
ALTER TABLE ET_MENSAJES_FARMACIAS ADD FOREIGN KEY (C_ID_USUARIO_ENVIA) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_PAGOS ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_PAGOS ADD FOREIGN KEY (C_ID_PLAN) REFERENCES ET_PLANES(C_ID_PLAN);
ALTER TABLE ET_PAGOS_SUCURSAL ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_PAGOS_SUCURSAL ADD FOREIGN KEY (C_ID_PLAN) REFERENCES ET_PLANES(C_ID_PLAN);
ALTER TABLE ET_PAGOS_SUCURSAL ADD FOREIGN KEY (C_ID_SUCURSAL) REFERENCES ET_SUCURSAL(C_ID_SUCURSAL);
ALTER TABLE ET_PACIENTE ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_PACIENTE ADD FOREIGN KEY (C_ID_COMUNA) REFERENCES ET_COMUNA(C_ID_COMUNA);
ALTER TABLE ET_PUNTUACION ADD FOREIGN KEY (C_ID_SOLICITUD) REFERENCES ET_SOLICITUD(C_ID_SOLICITUD);
ALTER TABLE ET_REPRESENTANTES ADD FOREIGN KEY (C_ID_USUARIO) REFERENCES ET_USUARIOS(C_ID_USUARIO);
ALTER TABLE ET_REPRESENTANTES ADD FOREIGN KEY (C_ID_FARMACIA) REFERENCES ET_FARMACIA(C_ID_FARMACIA);
ALTER TABLE ET_REPRESENTANTE_SUCURSAL ADD FOREIGN KEY (C_ID_REPRESENTANTE) REFERENCES ET_REPRESENTANTES(C_ID_REPRESENTANTE);

INSERT INTO ET_REGION (D_NOMBRE_REGION,S_ORDINAL_REGION)
VALUES
	('Arica y Parinacota','XV'),
	('Tarapacá','I'),
	('Antofagasta','II'),
	('Atacama','III'),
	('Coquimbo','IV'),
	('Valparaiso','V'),
	('Metropolitana de Santiago','RM'),
	('Libertador General Bernardo O\'Higgins','VI'),
	('Maule','VII'),
	('Biobío','VIII'),
	('Ñuble','XVI'),
	('La Araucanía','IX'),
	('Los Ríos','XIV'),
	('Los Lagos','X'),
	('Aisén del General Carlos Ibáñez del Campo','XI'),
	('Magallanes y de la Antártica Chilena','XII');

INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(1,'Arica');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(1,'Camarones');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(1,'Putre');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(1,'General Lagos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Alto Hospicio');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Iquique');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Pozo Almonte');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Camiña');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Colchane');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Huara');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(2,'Pica');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Antofagasta');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Mejillones');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Sierra Gorda');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Taltal');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Calama');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Ollagüe');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'San Pedro de Atacama');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'Tocopilla');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(3,'María Elena');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Copiapó');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Caldera');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Tierra Amarilla');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Chañaral');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Diego de Almagro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Vallenar');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Alto del Carmen');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Freirina');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(4,'Huasco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'La Serena');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Coquimbo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Andacollo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'La Higuera');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Paihuano');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Vicuña');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Illapel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Canela');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Los Vilos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Salamanca');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Ovalle');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Combarbalá');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Ovalle');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Monte Patria');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Punitaqui');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(5,'Río Hurtado');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Valparaiso');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Casablanca');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Concón');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Juan Fernández');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Puchuncaví');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Quintero');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Viña del Mar');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Isla de Pascua');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Los Andes');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Calle Larga');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Rinconada');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'San Esteban');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'La Ligua');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Cabildo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Papudo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Petorca');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Zapallar');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Quillota');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'La Calera');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Hijuelas');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'La Cruz');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Nogales');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'San Antonio');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Algarrobo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Cartagena');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'El Quisco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'El Tabo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Santo Domingo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Catemu');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Llay Llay');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Panquehue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Putaendo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Santa María');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Quilpué');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Limache');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Olmué');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(6,'Villa Alemana');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Santiago');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Cerrillos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Cerro Navia');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Conchalí');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'El Bosque');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Estación Central');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Huechuraba');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Independencia');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'La Cisterna');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'La Florida');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'La Granja');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'La Pintana');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'La Reina');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Las Condes');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Lo Barnechea');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Lo Espejo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Lo Prado');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Macul');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Maipú');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Ñuñoa');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Pedro Aguirre Cerda');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Peñalolén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Providencia');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Pudahuel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Quilicura');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Quinta Normal');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Recoleta');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Renca');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'San Joaquín');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'San Miguel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'San Ramón');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Vitacura');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Puente Alto');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Pirque');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'San José de Maipo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Colina');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Lampa');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Tiltil');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'San Bernardo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Buin');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Calera de Tango');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Paine');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Melipilla');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Alhué');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Curacaví');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'María Pinto');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Curacaví');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'San Pedro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Talagante');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'El Monte');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Isla de Maipo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Padre Hurtado');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(7,'Peñaflor');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Rancagua');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Codegua');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Coinco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Coltauco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Doñihue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Graneros');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Las Cabras');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Machalí');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Malloa');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Mostazal');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Olivar');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Peumo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Pichidegua');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Quinta de Tilcoco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Rengo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Requínoa');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'San Vicente');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Pichilemu');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'La Estrella');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Litueche');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Marchihue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Navidad');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Paredones');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'San Fernando');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Chépica');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Chimbarongo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Lolol');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Nancagua');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Palmilla');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Peralillo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Placilla');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Pumanque');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(8,'Santa Cruz');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Talca');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Constitucion');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Curepto');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Empedrado');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Maule');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Pelarco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Pencahue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Río Claro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'San Clemente');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'San Rafael');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Cauquenes');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Chanco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Pelluhue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Curicó');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Hualañé');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Licantén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Molina');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Rauco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Romeral');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Sagrada Familia');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Teno');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Vichuquén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Linares');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Colbún');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Longaví');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Parral');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Retiro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'San Javier');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Villa Alegre');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(9,'Yerbas Buenas');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Concepcion');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Coronel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Chiguayante');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Florida');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Hualqui');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Lota');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Penco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'San Pedro de la Paz');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Santa Juana');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Talcahuano');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Tomé');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Hualpén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Lebu');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Arauco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Cañete');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Contulmo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Curanilahue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Los Álamos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Tirúa');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Los Ángeles');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Antuco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Cabrero');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Laja');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Mulchén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Nacimiento');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Negrete');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Quilaco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Quilleco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'San Rosendo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Santa Bárbara');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Tucapel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Yumbel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(10,'Alto Biobío');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Chillán');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Bulnes');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Chillán Viejo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'El Carmen');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Pemuco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Pinto');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Quillón');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'San Ignacio');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Yungay');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Cobquecura');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Coelemu');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Ninhue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Portezuelo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Quirihue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Ránquil');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Treguaco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Coihueco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'Ñiquén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'San Carlos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'San Fabián');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(11,'San Nicolás');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Temuco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Carahue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Cunco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Curarrehue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Freire');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Galvarino');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Gorbea');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Lautaro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Loncoche');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Melipeuco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Nueva Imperial');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Padre las Casas');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Perquenco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Pitrufquén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Saavedra');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Teodoro Schmidt');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Toltén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Vilcún');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Villarrica');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Cholchol');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Angol');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Collipulli');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Curacautín');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Ercilla');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Lonquimay');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Los Sauces');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Lumaco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Purén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Renaico');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Traiguén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(12,'Victoria');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Valdivia');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Corral');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Lanco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Los Lagos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Máfil');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Mariquina');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Paillaco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Panguipulli');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'La Unión');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Futrono');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Lago Ranco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(13,'Río Bueno');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Puerto Montt');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Calbuco');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Cochamó');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Fresia');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Frutillar');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Los Muermos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Llanquihue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Maullín');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Puerto Varas');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Castro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Ancud');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Chonchi');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Curaco de Vélez');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Dalcahue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Puqueldón');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Queilén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Quellón');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Quemchi');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Quinchao');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Osorno');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Puerto Octay');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Purranque');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Puyehue');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Río Negro');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'San Juan de la Costa');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'San Pablo');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Chaitén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Futaleufú');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Hualaihué');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(14,'Palena');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Coyhaique');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Lago Verde');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Aysén');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Cisnes');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Guaitecas');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Cochrane');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'O''Higgins');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Tortel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Chile Chico');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(15,'Río Ibáñez');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Punta Arenas');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Laguna Blanca');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Río Verde');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'San Gregorio');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Cabo de Hornos');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Antártica');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Porvenir');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Primavera');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Timaukel');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Natales');
INSERT INTO ET_COMUNA(C_ID_REGION, D_NOMBRE_COMUNA) VALUES(16,'Torres del Paine');

INSERT INTO ET_ESPECIALIDAD(D_ESPECIALIDAD) VALUES('Enfermeria');
INSERT INTO ET_ESPECIALIDAD(D_ESPECIALIDAD) VALUES('Medicina');
INSERT INTO ET_ESPECIALIDAD(D_ESPECIALIDAD) VALUES('Kinesiología');
INSERT INTO ET_ESPECIALIDAD(D_ESPECIALIDAD) VALUES('Terapia Ocupacional');
INSERT INTO ET_ESPECIALIDAD(D_ESPECIALIDAD) VALUES('Masoterapia');
INSERT INTO ET_ESPECIALIDAD(D_ESPECIALIDAD) VALUES('Podología');

INSERT INTO ET_TIPO_USUARIO(D_TIPO_USUARIO) VALUES('Administrador');
INSERT INTO ET_TIPO_USUARIO(D_TIPO_USUARIO) VALUES('Cliente');
INSERT INTO ET_TIPO_USUARIO(D_TIPO_USUARIO) VALUES('Profesional de la salud');
INSERT INTO ET_TIPO_USUARIO(D_TIPO_USUARIO) VALUES('Representante de farmacia');
INSERT INTO ET_TIPO_USUARIO(D_TIPO_USUARIO) VALUES('Representante de sucursal');

INSERT INTO ET_ESTADO_CUENTA(D_ESTADO_CUENTA) VALUES('Pendiente de activación');
INSERT INTO ET_ESTADO_CUENTA(D_ESTADO_CUENTA) VALUES('Activa');
INSERT INTO ET_ESTADO_CUENTA(D_ESTADO_CUENTA) VALUES('Suspendida');
INSERT INTO ET_ESTADO_CUENTA(D_ESTADO_CUENTA) VALUES('Pendiente de eliminación');

INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(1,83,2,'111-2','Administrador','1','administrador1@easysalud.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(1,83,2,'112-0','Administrador','2','administrador2@easysalud.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(2,83,2,'113-9','Cliente','1','cliente1@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(2,83,2,'114-7','Cliente','2','cliente2@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(3,83,2,'115-5','Profesional','1','profesional1@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(3,83,2,'116-3','Profesional','2','profesional2@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(4,83,2,'117-1','Representante Farmacia','1','farmacia1@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(4,83,2,'118-K','Representante Farmacia','2','farmacia2@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(5,83,2,'119-8','Representante Sucursal','1','sucursal1@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');
INSERT INTO ET_USUARIOS(C_ID_TIPO_USUARIO,C_ID_COMUNA,C_ID_ESTADO_CUENTA,S_RUN_USUARIO,D_NOMBRE_USUARIO,D_APELLIDO_USUARIO,D_EMAIL_USUARIO,N_MOVIL_USUARIO,D_DIRECCION_USUARIO,D_CLAVE_USUARIO,F_FECHA_NACIMIENTO,D_CODIGO_USUARIO) VALUES(5,83,2,'120-1','Representante Sucursal','2','sucursal2@correo.cl',999999999,'Dirección','abc123','2000-10-21','123');

INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Tecnico');
INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Universitario');
INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Capacitacion');
INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Diplomado');
INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Magister');
INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Postgrado');
INSERT INTO ET_NIVEL_ESTUDIOS(D_NOMBRE_NIVEL_ESTUDIOS) VALUES('Especializacion');

INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Academia de Humanismo Cristiano');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Adolfo Ibáñez');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Alberto Hurtado');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Andrés Bello');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Arturo Prat');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Autónoma de Chile');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Bernardo O''Higgins');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Bolivariana');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Católica de Chile');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Católica Silva Henríquez');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Central de Chile');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad de Chile');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad de Las Américas');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad del Desarrollo');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad de los Andes');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad de Los Lagos');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad del Pacífico');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad de Santiago de Chile');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Diego Portales');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Finis Terrae');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Gabriela Mistral');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad SEK');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad La República');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Mayor');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Miguel de Cervantes');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Pedro de Valdivia');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad San Sebastián');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Santo Tomás');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Técnica Federico Santa María');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Tecnológica de Chile INACAP');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad Tecnológica Metropolitana ');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad UCINF');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Universidad UNIACC');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Ceitec');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Crecic ');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Crownliet ');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Duoc UC');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Gamma');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Guillermo González Heinrich');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica ICCE');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica ICEL');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica IDMA');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica INACAP');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Insalco');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Intec');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica ITC');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica John F. Kennedy');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Laplace');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Paulina Diard');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica ProAndes');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Salesianos Don Bosco');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Santo Tomás');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Centro de formación técnica Zipter');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional AIEP');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Antares');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Arcos');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Carlos Casanueva');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Cenafom');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Ciisa');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Duoc UC');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Eatri');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional ECAS');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional ENAC');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional INACAP');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional INAF');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional de Chile');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional IPP');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Iplacex');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional La Araucana');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Los Leones');
INSERT INTO ET_INSTITUCIONES(D_NOMBRE_INSTITUCION) VALUES('Instituto profesional Santo Tomás');

INSERT INTO ET_ESTADO(D_NOMBRE_ESTADO) VALUES('Solicitado');
INSERT INTO ET_ESTADO(D_NOMBRE_ESTADO) VALUES('Aceptado');
INSERT INTO ET_ESTADO(D_NOMBRE_ESTADO) VALUES('Confirmado');
INSERT INTO ET_ESTADO(D_NOMBRE_ESTADO) VALUES('Finalizada');
INSERT INTO ET_ESTADO(D_NOMBRE_ESTADO) VALUES('Cancelado');
INSERT INTO ET_ESTADO(D_NOMBRE_ESTADO) VALUES('Rechazado');

INSERT INTO ET_PROFESIONAL (C_ID_USUARIO,C_ID_COMUNA,D_IMAGEN,D_DESCRIPCION,L_ACTIVO,L_PREMIUM,D_DIRECCION_DISPONIBILIDAD,N_LATITUD,N_LONGITUD) VALUES ('5','83','0','Profesion 1 descripcion',TRUE,FALSE,'Prueba','0','0');
INSERT INTO ET_PROFESIONAL (C_ID_USUARIO,C_ID_COMUNA,D_IMAGEN,D_DESCRIPCION,L_ACTIVO,L_PREMIUM,D_DIRECCION_DISPONIBILIDAD,N_LATITUD,N_LONGITUD) VALUES ('6','83','0','Profesion 2 descripcion',TRUE,FALSE,'Prueba','0','0');

INSERT INTO ET_ESTUDIOS_PROFESIONAL (C_ID_PROFESIONAL,C_ID_ESPECIALIDAD,C_ID_NIVEL_ESTUDIOS,C_ID_INSTITUCIONES,D_TITULO) VALUES ('1','1','1','1','Titulo Profesional 1');
INSERT INTO ET_ESTUDIOS_PROFESIONAL (C_ID_PROFESIONAL,C_ID_ESPECIALIDAD,C_ID_NIVEL_ESTUDIOS,C_ID_INSTITUCIONES,D_TITULO) VALUES ('2','2','2','2','Titulo Profesional 2');

INSERT INTO ET_DISPONIBILIDAD (C_ID_PROFESIONAL,L_LUNES,L_MARTES,L_MIERCOLES,L_JUEVES,L_VIERNES,L_SABADO,L_DOMINGO,F_HORAS_DESDE,F_MINUTOS_DESDE,F_HORAS_HASTA,F_MINUTOS_HASTA) VALUES('1',TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,'13','00','16','00');
INSERT INTO ET_DISPONIBILIDAD (C_ID_PROFESIONAL,L_LUNES,L_MARTES,L_MIERCOLES,L_JUEVES,L_VIERNES,L_SABADO,L_DOMINGO,F_HORAS_DESDE,F_MINUTOS_DESDE,F_HORAS_HASTA,F_MINUTOS_HASTA) VALUES('2',FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,'18','00','20','00');

INSERT INTO ET_EQUIPAMIENTO (C_ID_PROFESIONAL,D_EQUIPO,D_IMAGEN) VALUES ('1','Estetoscopio','images/equip/1.png');
INSERT INTO ET_EQUIPAMIENTO (C_ID_PROFESIONAL,D_EQUIPO,D_IMAGEN) VALUES ('2','Estetoscopio','images/equip/2.png');